F0112 23:10:37.804463 32040 32040 raylet_client.cc:57] Could not connect to socket /tmp/pminervi-32040-ray/session_2021-01-12_23-07-49_524089_32040/sockets/raylet
*** Check failure stack trace: ***
    @     0x2b7bae64910d  google::LogMessage::Fail()
    @     0x2b7bae64a57c  google::LogMessage::SendToLog()
    @     0x2b7bae648de9  google::LogMessage::Flush()
    @     0x2b7bae649001  google::LogMessage::~LogMessage()
    @     0x2b7bae5fc479  ray::RayLog::~RayLog()
    @     0x2b7bae3178bf  ray::raylet::RayletConnection::RayletConnection()
    @     0x2b7bae318bd0  ray::raylet::RayletClient::RayletClient()
    @     0x2b7bae2bc12b  ray::CoreWorker::CoreWorker()
    @     0x2b7bae2bfce4  ray::CoreWorkerProcess::CreateWorker()
    @     0x2b7bae2c0f52  ray::CoreWorkerProcess::CoreWorkerProcess()
    @     0x2b7bae2c192b  ray::CoreWorkerProcess::Initialize()
    @     0x2b7bae1f1de6  __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
    @     0x2b7bae1f3595  __pyx_tp_new_3ray_7_raylet_CoreWorker()
    @     0x5604b8abb715  type_call
    @     0x5604b8a3492b  _PyObject_FastCallDict
    @     0x5604b8abb57e  call_function
    @     0x5604b8ae038a  _PyEval_EvalFrameDefault
    @     0x5604b8ab4bfe  _PyEval_EvalCodeWithName
    @     0x5604b8ab5771  fast_function
    @     0x5604b8abb505  call_function
    @     0x5604b8ae1147  _PyEval_EvalFrameDefault
    @     0x5604b8ab68c6  PyEval_EvalCodeEx
    @     0x5604b8ab71a6  function_call
    @     0x5604b8a3454e  PyObject_Call
    @     0x5604b8ae1a6c  _PyEval_EvalFrameDefault
    @     0x5604b8ab553b  fast_function
    @     0x5604b8abb505  call_function
    @     0x5604b8ae038a  _PyEval_EvalFrameDefault
    @     0x5604b8ab6289  PyEval_EvalCodeEx
    @     0x5604b8ab701c  PyEval_EvalCode
    @     0x5604b8b393c4  run_mod
    @     0x5604b8b397c1  PyRun_FileExFlags
